/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ContactIndexRouteImport } from './routes/contact.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ProductsSlugIndexRouteImport } from './routes/products.$slug.index'
import { Route as ProductsSlugIdRouteImport } from './routes/products.$slug.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugIndexRoute = ProductsSlugIndexRouteImport.update({
  id: '/products/$slug/',
  path: '/products/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugIdRoute = ProductsSlugIdRouteImport.update({
  id: '/products/$slug/$id',
  path: '/products/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/$id': typeof ProductsSlugIdRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/$slug/$id': typeof ProductsSlugIdRoute
  '/products/$slug': typeof ProductsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/$id': typeof ProductsSlugIdRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/contact/'
    | '/products/'
    | '/products/$slug/$id'
    | '/products/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/products'
    | '/products/$slug/$id'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/contact/'
    | '/products/'
    | '/products/$slug/$id'
    | '/products/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsSlugIdRoute: typeof ProductsSlugIdRoute
  ProductsSlugIndexRoute: typeof ProductsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug/': {
      id: '/products/$slug/'
      path: '/products/$slug'
      fullPath: '/products/$slug/'
      preLoaderRoute: typeof ProductsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug/$id': {
      id: '/products/$slug/$id'
      path: '/products/$slug/$id'
      fullPath: '/products/$slug/$id'
      preLoaderRoute: typeof ProductsSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsSlugIdRoute: ProductsSlugIdRoute,
  ProductsSlugIndexRoute: ProductsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
